### ISSUE TITLE
The system version supported by the instance

### ISSUE THREAD

**Issue by LYXmoonstars** [apache/cloudstack#2532]
I want to create examples of various systems, but I don't know that cloudstack specifically supports those systems and the version number of the system.

**Comment by rafaelweingartner** [comment]
I will close this issue. The issues tab here is not intended to look for answers for doubts. You can try using IRC, Slack, or our mailing lists. Please visit [1].

[1] https://cloudstack.apache.org/mailing-lists.html

**Comment by DaanHoogland** [comment]
@rafaelweingartner , If @LYXmoonstars want to create a list of versions supported, that would be a feature of the eco system wouldn't it? Maybe not for the system itself but for the tests or documentation. If you only want an answer to a question, @LYXmoonstars , this is indeed not the place.

**Comment by rafaelweingartner** [comment]
Well, I closed because it felt like a question, and not a report of an issue to improve our documentation. 
It was not clear if he was talking about operating system for VMs, or hypervisors' operating systems that are supported by ACS.

There is another issue that @LYXmoonstars just opened, and it was a question. That is why I assumed this one was the same type. The other one I did not close yet, let's see if the replies use there.
