### ISSUE TITLE
HTML shown to end-user in UI

### ISSUE THREAD

**Issue by jorgesumle** [apache/cloudstack#2575]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11.0.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Any OS

##### SUMMARY

HTML code (`<br/><br/>`) in the UI

![captura](https://user-images.githubusercontent.com/14212780/38812472-a0f266ee-418c-11e8-8c5d-d7c1541b2dfa.png)

##### STEPS TO REPRODUCE

~~~
Create a zone
~~~

##### EXPECTED RESULTS

~~~
non-HTML text
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by resmo** [comment]
enviroment? os?

what OS is this, what browser in which version.

**Comment by rhtyd** [comment]
@jorgesumle Supported browsers for current UI are Chrome/Chromium and Firefox. We usually don't test against other browsers. However, I was able to see this in Chrome.

**Comment by rhtyd** [comment]
I could reproduce this in latest 4.11 while creating zone.

**Comment by PaulAngus** [comment]
i *think* that the issue is with <br/><br/>
<br/> is pure XHTML, we should ether use HTML <br> or the hybrid which would be <br />  (with a space).

There are a few of these <br/><br/> knocking around, and the output depends on whether the browser can figure it out for itself or not (it renders ok for me using Chrome on Windows).

cc @rhtyd

**Comment by PaulAngus** [comment]
@ernjvr has a fix, PR will be coming along fairly soon

**Comment by ernjvr** [comment]
Please review fix: https://github.com/apache/cloudstack/pull/2814

**Comment by rhtyd** [comment]
4.11.2.0 PR: https://github.com/apache/cloudstack/pull/2815
