### ISSUE TITLE
Why do we package final artifacts with developer profile?

### ISSUE THREAD

**Issue by khos2ow** [apache/cloudstack#2620]
This technically is not an issue, but I was just got curios why we package our final artifacts (both rpm and deb) with `developer` maven profile. in:

- `debian/rules#L16`
- `packaging/centos63/cloud.spec#L209-223`
- `packaging/centos7/cloud.spec#L192`

It doesn't make sense since these are going to be installed in `prod` or alike, and most probably won't be any `deploydb` and `db.properties.override`.

I believe we should remove these.

**Comment by rhtyd** [comment]
@khos2ow there is no need to enable the `developer` profile, and enabling the profile causes no difference to the built rpm, deb files.

**Comment by rhtyd** [comment]
With the `developer` profile enabled, maven modules for test and tools are added to the build tree which is why it is needed as the rpm/deb create the marvin and integration-test pkgs. See https://github.com/apache/cloudstack/blob/master/pom.xml#L1187

Since the question has been answered, I'll close this. If you need to send any change, please directly submit a PR, thanks.
