### ISSUE TITLE
Host is still unsecured when provisionCertificate api is called

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#2763]
##### SUMMARY

When provisionCertificate api is executed the host ends up in unsecured state, instead should be secured

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, agent
~~~

##### CLOUDSTACK VERSION

~~~
4.12
~~~

##### CONFIGURATION

ca.framework.cert.automatic.renewal = true
ca.plugin.root.allow.expired.cert = true
ca.plugin.root.auth.strictness = false

##### OS / ENVIRONMENT

NA

##### STEPS TO REPRODUCE

~~~
execute provisionCertificate api with a random kvm host with/out recconect=true, the api call is successful but connection is unsecured. 
~~~

##### EXPECTED RESULTS

~~~
Connection is secured 
~~~

##### ACTUAL RESULTS

~~~
Connection is unsecured 

~~~

[agent_unsecured.txt](https://github.com/apache/cloudstack/files/2222393/agent_unsecured.txt)
[unsecured_connection.txt](https://github.com/apache/cloudstack/files/2222394/unsecured_connection.txt)

**Comment by borisstoyanov** [comment]
ping @rhtyd and @dhlaluku. Could this be related to these changes: #2756

**Comment by dhlaluku** [comment]
@borisstoyanov I do not think so, that small fix that I did was for the NPE issue. The VM lifecycle tests have already been failing before and I think it might be due to regressions in provisionCertificate API itself that need looking into. Perhaps @rhtyd can help us here since he authored the Secure live migration feature.
