### ISSUE TITLE
VMware basic zone VR fails to start and get private IP

### ISSUE THREAD

**Issue by rhtyd** [apache/cloudstack#3031]
VMware basic zone does not support host-level firewall (SG), but there could be a use-case to have a basic zone setup with no isolation. Currently, the VR for the default basic zone guest network VR fails to start (gets stuck in Starting state for a long time) due to incorrect `eth1` IP/netmask. Screenshot from 4.9 VR:
![screenshot from 2018-11-15 09-24-05](https://user-images.githubusercontent.com/95203/48529497-58ba5380-e8b9-11e8-81a5-faabdf774561.png)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR, Basic Zone, VMware
~~~

##### CLOUDSTACK VERSION

~~~
Found in 4.9, 4.11, master
~~~

##### CONFIGURATION

Basic zone with VMware 5.5u3, 6.5

##### STEPS TO REPRODUCE

~~~
- Deploy basic zone in VMware
- Deploy a guest VM
- Guest network VR will be stuck
- The /var/cache/cloud/cmdline will have 0.0.0.0 as eth1 ip/netmask
~~~

##### EXPECTED RESULTS

~~~
While SG does not work for VMware+basic zone, VR should start and get a private IP (eth1)
~~~

##### ACTUAL RESULTS

~~~
VR stuck in starting state, guest VM eventually fails to start. VR's eth1 does not get a valid IP.
~~~

**Comment by andrijapanicsb** [comment]
@rhtyd do we have time for this one - or should we move it to 4.15 milestone?

**Comment by DaanHoogland** [comment]
@andrijapanicsb basic zones are being phased out in favour of shared networks (with security groups) So I think postponng means canceling in this case.

**Comment by andrijapanicsb** [comment]
whatever we decide, I'm fine with it.

**Comment by DaanHoogland** [comment]
i think we can lower priority but not close yet. @rhtyd ?

**Comment by rhtyd** [comment]
I guess nobody reported this as this was perhaps broken (at least since 4.7, definitely 4.9/4.11?) and nobody uses VMware with basic zone. @DaanHoogland if it's broken indeed let's try and fix in next major release, I don't think it's a blocker if nobody has reported it.

**Comment by PaulAngus** [comment]
I 100% disagree.

because we do not know if someone using VMware with basic zones, and because we assume that anyone who does must have upgraded recently to find it broken, does not mean that it is not used.

Also basic zones are the default type, someone new to CloudStack may try vmware with a basic zone, find that it doesn't work at all and abandon it.

**Comment by rhtyd** [comment]
@PaulAngus that's a valid argument making it hard to not disagree with you :)

Let's try the first thing to try and reproduce this against 4.13.0.0 or latest 4.13 or master/4.14. @PaulAngus @andrijapanicsb @DaanHoogland - does Trillian support basic zone deployment with VMWare or something we would need to test manually?

**Comment by DaanHoogland** [comment]
I have started a basic zone in vmware, systemvms are running. Also, unless some work or user is actually blocked, it is not a blocker. Potential problems are only problems if they arise. We cannot support features indefinitely without feedback from actual users.

**Comment by rhtyd** [comment]
@DaanHoogland did you try deploying a user VM that would spin up a VR, the issue was seen VR stuck in starting state.

**Comment by DaanHoogland** [comment]
the smoke tests are running for an hour now. all fine ;)
<img width="240" alt="image" src="https://user-images.githubusercontent.com/2486961/75683647-d3b6a180-5c97-11ea-87b0-3604156cab80.png">

health checks are failing though, not sure if these are an issue in basic zone. but the router(s?) are up. weird stuff but unrelated:
<img width="953" alt="image" src="https://user-images.githubusercontent.com/2486961/75683719-f21c9d00-5c97-11ea-9172-a5279cfc5cf0.png">

**Comment by DaanHoogland** [comment]
ok, the env won't deploy a VM because network is not available, re-opening.

**Comment by DaanHoogland** [comment]
reinstalled a 4.11.3; systemvm come up but the console proxy does shows consoles for neither cpvm nor ssvm.
registering a template works. (ssvm works, as it is confirmed present on teh backend storage)

**Comment by DaanHoogland** [comment]
same symptoms in 4.9.3.1; ip 0.0.0.0 is send for eth1.

**Comment by DaanHoogland** [comment]
double checked 4.9 kvm works fine

**Comment by andrijapanicsb** [comment]
If this is broken since 4.8 and ZERO people (community users) raised a bug, I would suggest this should be addressed in the next release @rhtyd @PaulAngus @DaanHoogland, not now

**Comment by rhtyd** [comment]
We can all agree with @PaulAngus 's comment and ideally should be fixing this. Per git history, this regression got introduced some ~4 years ago. How about after the branch freeze, let's see if it's a quick enough fix. Otherwise, I'm okay to address in a near-term minor release or next major.

**Comment by andrijapanicsb** [comment]
@rhtyd @PaulAngus we need this one done before 4.14 is out
Any suggestions?

**Comment by harikrishna-patnala** [comment]
Working on this to fix the issue. I could point out the exact place where nic configuring is being skipped and made the code changes accordingly in PR https://github.com/apache/cloudstack/pull/3977


![Screen Shot 2020-03-25 at 12 25 54 PM](https://user-images.githubusercontent.com/3348673/77514122-40d6e480-6e9c-11ea-82f6-6f16141eb471.png)

With that eth1 on VR is configured with private IP but VR is still stuck in starting state because it is not able to run checkSshCommand on port 3922

2020-03-25 06:57:18,683 INFO  [c.c.h.v.r.VmwareResource] (DirectAgent-336:ctx-7579bce4 10.2.3.159, job-37/job-38, cmd: CheckSshCommand) (logid:b696c8c5) **Trying to connect to 10.2.5.224**
2020-03-25 06:57:18,686 INFO  [c.c.h.v.r.VmwareResource] (DirectAgent-336:ctx-7579bce4 10.2.3.159, job-37/job-38, cmd: CheckSshCommand) (logid:b696c8c5) **Could not connect to 10.2.5.224 due to java.net.ConnectException: Connection refused**

VR Iptables has input chain configured on eth1 3922 port and packets are hitting.

Can someone help me debugging further on what is missing in terms of connectivity

**Comment by harikrishna-patnala** [comment]
I figured out the issue and PR is updated with the fix.
