### ISSUE TITLE
Copy template/iso tags into VM

### ISSUE THREAD

**Issue by bwsw** [apache/cloudstack#3048]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.12
~~~

##### SUMMARY

Add a special attribute to `deployVirtualMachine` which help to copy tags to a virtual machine from originally selected ISO or template. This is beneficial if the tags must be distributed to VMs.

##### STEPS TO REPRODUCE

CloudStack-UI and other interfaces may want to distribute tags from installation sources to deployed VMs for later use. This feature helps to address that.

~~~

~~~

##### EXPECTED RESULTS

~~~
Tags are created for VM when deployed from a template/ISO when appropriate attribute is set.
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by anuragaw** [comment]
I'd like to work on it @bwsw . Please let me know if that works for you.

**Comment by ustcweizhou** [comment]
@bwsw @anuragaw 
I do not understand what's the proposal of this request.
in my opinion, templete/iso tag should be taken into consideration when deploy/start/migrate a vm. for now, it is not working well in cloudstack. we can fix the issues instead of copying the tags into vm attributes.

**Comment by anuragaw** [comment]
@ustcweizhou - Apologies for the very late reply. I think the goal here is to allow users to optionally call for copying tags from iso/templates into VMs. This can something as below -

`deployVituamMachine ...... copyTemplateOrIsoTags=true` ...the flag can be default to false so that the default behaviour remains as it is currently.
