### ISSUE TITLE
Access to online documentation is not public

### ISSUE THREAD

**Issue by ANKerD** [apache/cloudstack#3167]
##### ISSUE TYPE

 * Documentation Report

##### COMPONENT NAME

~~~
DOCS
~~~

##### CLOUDSTACK VERSION

~~~
Latest
~~~

##### OS / ENVIRONMENT

Google Chrome 

##### SUMMARY

I was readin about primary storage [here](http://docs.cloudstack.apache.org/projects/cloudstack-administration/en/4.8/storage.html#primary-storage) and tried to open [this link](http://docs.cloudstack.apache.org/en/latest/concepts.html#about-primary-storage) to learn more and endedup with a no permission message.

**Comment by richardlawley** [comment]
The documentation _is_ public, just that the documentation seems to show permission denied instead of 404 for a broken link.  You're viewing the old archived documentation - if you start from the [main site](http://docs.cloudstack.apache.org/) you'll get the latest documentation.

Latest version of the links you're trying to view: http://docs.cloudstack.apache.org/en/4.11.2.0/adminguide/storage.html and http://docs.cloudstack.apache.org/en/4.11.2.0/conceptsandterminology/concepts.html#about-primary-storage

**Comment by ANKerD** [comment]
Thanks :)
