### ISSUE TITLE
savepassword.sh crashes router when starting many VMs at once

### ISSUE THREAD

**Issue by onitake** [apache/cloudstack#3180]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
All versions since 488625b1937eeb38f9a29706b6e7333043ae3e6e
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

We discovered a serious bug in one of the System VM scripts: /systemvm/debian/opt/cloud/bin/savepassword.sh

The way I understand this script, it is supposed to clear out stored passwords for the password reset API by sending "ack" requests (="saved_password") to the password reset server running locally.

But instead of just sending a single request per VM, it tries to execute curl for *all* IP addresses assigned to the VR, and on top of that, this happens *every* time a VM is launched.

If there are only a small number of VMs launched concurrently or only a handful of NAT IPs configured on this router, the number of requests is small. Otherwise, there will be many curl processes waiting for a reply. These may even lock the router up due to process/memory contention (or some sort of deadlock). It's not entirely clear to me why curl would linger instead fast-failing.

It seems this was introduced in CLOUDSTACK-8331 and I don't understand why the request can't be simply sent to http://127.0.0.1:8080 *once*?

##### STEPS TO REPRODUCE

1. Set up an isolated network with NAT
2. Allocate many NAT addresses on this network (ex. more than 100)
3. Install many VMs and attach them to this network (ex. more than 100)
4. Configure static NAT for each VM
5. Stop and start all VMs at the same time

##### EXPECTED RESULTS

The VMs start and are available on the network.

##### ACTUAL RESULTS

The virtual router locks up/crashes/reboots.
In older CloudStack VR versions, this even led to a complete network lockup (due to the router starting without configuration). In the Debian 9 version, it will probably simply reboot, causing a temporary outage, but possibly other problems.

**Comment by rhtyd** [comment]
What you've shared is the old password script and old mechanism. For kvm/xenserver/vmware now the password saving is handled by python based codebase: https://github.com/apache/cloudstack/blob/master/systemvm/debian/opt/cloud/bin/configure.py#L59

Here it does not blindly try to curl and save password by using a curl, but only to relevant running passwd_server_ip.py processes and ip/subnets (see code above). This, however, does not clear out any saved password, which is instead done by the client (guest VM) that should send a `saved_password` request which will remove the password and replace password saved in VR's password cache file with the string `saved_password`. In case of multi-tier VPCs etc, the password server can run on different subnets and therefore by historic design the password server needs to listen on each of the guest network/tiers, and the retrieve/save is done by interface.

The password server in 4.5 was process based and not scalable as it used file-based locks and forking mechanism. The 4.6-4.11+ password server is multi-threaded (not multi-process) and uses in-memory locks (not file based locks), the last time I benchmarked it, it beat the 4.5 version which is why we moved to python based password server. This was introduced in https://github.com/apache/cloudstack/commit/375e998eafdb5a02385f5330fea89942ebb2d02a

In 4.11, the configurations are persistent on the VR. That is once the VR is patched, it does not lose the configuration even if it may get restarted. What you've shared does not check with the design, however, we can investigate possible bottlenecks and cases that may be causing side-effects in the VR.

**Comment by onitake** [comment]
That is great news, thanks a lot for the insight, Rohit.

Since we'll be moving to 4.11 soon, the old VR templates will make way for the new one.
I wonder though why the savepassword.sh script is still in the repo, if the password reset feature is now handled entirely by configure.py.

I already know that router configs are now persistent, so even if it crashes, there will no longer be an unconfigured network after reboot. It's another feature I'm looking forward to in CloudStack 4.11.

As for the immediate issue: We'll try to limit the number of VMs that are started at once. Perhaps this will allow the lingering curl processes to time out and prevent a crash. Better suggestions would be very welcome, of course.

**Comment by rhtyd** [comment]
@onitake Many of the shell scripts have been moved to python based codebase, however, they exist as some of the hypervisor plugins such as hyper-v and ovm3 still use them instead of the new codebase. I'm performing some scalability tests against the VR password server on a vmware (5.5u3) based environment for isolated networks, I'll share them soon.

**Comment by rhtyd** [comment]
From ab/benchmarking point of view, the default VR offering has a single core and limited RAM (256MB). It may be increased for the network to remedy networks where high VM start/stop throughputs are necessay so the VR can handle multi-process curl/password-saving workloads. 

To simulate 100VM starts with 10Vms requests concurrent, here are the results:
```
# time xargs -I % -P 10 curl --header "DomU_Request: save_password" http://10.1.1.1:8080 -F "ip=10.1.1.11" -F "password=alskfdj" -F "token=6ef12f18f97d25cafac7305afa7ead10" < <(printf '%s\n' {1..100})

real	0m10.631s
user	0m0.796s
sys	0m0.260s
```
And in another test with 100 concurrent requests and for upto 1000VMs:
```
root@r-4-VM:~# time xargs -I % -P 100 curl --header "DomU_Request: save_password" http://10.1.1.1:8080 -F "ip=10.1.1.11" -F "password=alskfdj" -F "token=6ef12f18f97d25cafac7305afa7ead10" < <(printf '%s\n' {1..1000})

real	0m16.411s
user	0m8.440s
sys	0m2.580s
```

I tried other permutations and combinations, but couldn't make the 4.11.2 VR crash. The obvious bottleneck discovered is to avoid forking of curl to make the http request, which in future could be done by the python code as well (multi-threaded than multi-process). I've opened a ticket to track future enhancement to the password server and configure.py: https://github.com/apache/cloudstack/issues/3182

**Comment by rhtyd** [comment]
Closing this issue, as wrt 4.11.2 VR the issue could not be reproduced. However, in 4.11.3+ we can attempt to further improve the password saving mechanism.
