### ISSUE TITLE
Removing, then adding kvm agent again occasionally fails

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3572]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
agent
~~~

##### CLOUDSTACK VERSION

~~~
4.13, master
~~~

##### SUMMARY

When deleting a host and then re-adding it again it fails

DEBUG:root:execute:systemctl stop cloudstack-agent
DEBUG:root:execute:sleep 30
DEBUG:root:execute:systemctl enable cloudstack-agent
DEBUG:root:execute:systemctl is-active cloudstack-agent
DEBUG:root:Failed to execute:failed

##### STEPS TO REPRODUCE

~~~
1. delete a host
2. Try to add it back
~~~

##### EXPECTED RESULTS

~~~
Host should be added 
~~~

##### ACTUAL RESULTS

~~~
After deleting agent is still running probably and adding fails
~~~

**Comment by DaanHoogland** [comment]
diag on this:
 in <prj-root>/python/lib/cloudutils/utilities.py,
  in the class ```serviceOpsRedhat7```,
   in method ```isServiceRunning(self, servicename)```,
 the service is checked by queriying the stdout of ```bash("systemctl is-active " + servicename)```.
 I'd rather have it check for the result instead of doing a textual check but haven't gotten this to work yet. Also I don't if and when the output changed during the EL7 lifecycle so my solution would be to check for both possible texts: ```"inactive"``` or ```"failed"```.
