### ISSUE TITLE
typo in error message

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3642]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### SUMMARY

Some typos in error message 

##### STEPS TO REPRODUCE

~~~
Import VM that does not match the service offering
~~~

##### EXPECTED RESULTS

~~~
should be 'match' and '!' should be removed
~~~

##### ACTUAL RESULTS

~~~
"errortext": "Failed to import VM: test! Service offering (cc5e76e7-f402-4fd1-b1e6-e53997430258) 3 CPU cores does not matches VM CPU cores 8  and VM is not in powered off state (Power state: PowerOn)!"
~~~
Another: 
~~~
    "errortext": "Failed to find unmanaged vm with name: c2-clone"
~~~
Should say: Couldn't find unmanaged vm with name: c2-clone in cluster1

**Comment by borisstoyanov** [comment]
@shwstppr can you have a look pls?

**Comment by shwstppr** [comment]
@borisstoyanov sure

**Comment by shwstppr** [comment]
@borisstoyanov Exclaimation issue was fixed with this change 6 days back, https://github.com/apache/cloudstack/pull/3606/commits/ffa90b96ac5bb854032be897213717949cbde3d9#diff-3eaaf9de1645091dff197645123e669cR800
Second fixed with,https://github.com/apache/cloudstack/pull/3606/commits/8381d2ae7403fff71d3c659d4f41578c3222e1d2

**Comment by deargopinath** [comment]
I just updated 3 error messages in the file named 'VmImportManagerImpl.java' to replace the word 'matches' with 'match'. The changes are in the branch named 'fix_3642'. I will submit the pull request shortly.
