### ISSUE TITLE
Under arm64 host environment VM console does not display properly

### ISSUE THREAD

**Issue by zhao21943266** [apache/cloudstack#3990]
Run cloudstack and agent in arm64 Ubuntu. At present, both the host and SVM are running. View the virtual machine through the console and it cannot be displayed. The prompt "guest has not initialized the display (yet)" is the same as that of opening the console through virt manager;The virtual machine is running normally and can enter the virtual machine through the virsh console f460826a-bb58-49ff-b446-955773abc513。
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
view console
~~~

##### CLOUDSTACK VERSION

~~~
4.13.1.0
~~~

##### CONFIGURATION

console proxy
##### OS / ENVIRONMENT

Ubuntu arm64
##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/52068346/77508699-40dbe200-6ea6-11ea-9cc6-abcdc3796a60.png)
![image](https://user-images.githubusercontent.com/52068346/77508758-69fc7280-6ea6-11ea-92ee-23e8a7cf5939.png)

~~~


~~~

**Comment by rhtyd** [comment]
@zhao21943266 the custom arm64 systemvmtemplate I had built was based on Debian9 where the console is disabled by default (to save RAM) which is why you don't see it. You may manually enable it to see it for systemvms/VRs, and for the guest VMs the console is enabled for Debian 10 guest template: http://dl.rohityadav.cloud/cloudstack-rpi/template/

Closing on this remark as this is not really a bug and the arm64 support is rather new and experimental (just my own experiment than something that is fully supported by the project).

**Comment by zhao21943266** [comment]
@rhtyd Thank you

**Comment by zhao21943266** [comment]
@rhtyd Hello, I tested that the image console of Debian 10 can display normally. Can you tell me how to manually start the Debian 9 system template console. Thank

**Comment by rhtyd** [comment]
@zhao21943266 you may google that I've not explored that myself the exact steps. I'll be updating new templates against Debian10 once 4.14 is out.

**Comment by rhtyd** [comment]
@zhao21943266 4.16 RC3 pkgs are here if you want to help test: http://download.cloudstack.org/arm64/4.16/
