### ISSUE TITLE
Fix error message for newer Libvirt/Qemu with UEFI based VMs cannot do VM snapshot

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#4184]
It seems newer libvirt/qemu cannot do snasphot of KVM domains if they use UEFI and the error `error: Operation not supported: internal snapshots of a VM with pflash based firmware are not supported` is seen in logs. Until the hypervisor side fixes this, this is not a CloudStack problem, however an internal error message is shown; perhaps we can check and throw a correct exception/error message.

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
KVM, UEFI-based VM, VM Snapshot
~~~

##### CLOUDSTACK VERSION

~~~
4.14/master
~~~

# virsh version
Compiled against library: libvirt 6.0.0
Using library: libvirt 6.0.0
Using API: QEMU 6.0.0
Running hypervisor: QEMU 4.2.0
Ubuntu 20.04 aarch64, but x86_64 issues seen as well

**Comment by boospy** [comment]
Yes same here.

**Comment by DaanHoogland** [comment]
trivial, marking for 4.16

**Comment by rhtyd** [comment]
Note - this happened only on RaspberryPi4/aarch64, however VM snapshots work on x86/Ubuntu etc.

**Comment by harikrishna-patnala** [comment]
There are some changes that went in the PR https://github.com/apache/cloudstack/pull/5297 where it updated the log message and tried to take the snapshot in a different way.

https://github.com/shapeblue/cloudstack/blob/81b7e6e750a581375612b78fbf04ce94da573839/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/KVMStorageProcessor.java#L1576

So I think it will solve this issue as well, but I could not verify or reproduce it due to lack of specific hardware.

@rohityadavcloud I think we can close this issue based on the changes in PR5297. Please confirm.

**Comment by rohityadavcloud** [comment]
Let me close this after checking this on a uefi systems (4.17 on rpi4)

**Comment by rohityadavcloud** [comment]
Couldn't completely check but closing on remarks above
