### ISSUE TITLE
Creating a network offering

### ISSUE THREAD

**Issue by gaaray2k** [apache/cloudstack#4229]
when I create a new network offering I give it a name and fill out all the require fields. I then enable the new offering but the new network offering doesnt show up when creating a new network. am I doing something wrong or is this a known bug?

version: 4.14

**Comment by DaanHoogland** [comment]
@gaaray2k I know the feeling bit in my experience this is a user issue. All requirements for a network offering have to be met for it to show in the list of offerings. check the create API call and compare it to the list offerings call that is done during create network procedure.

**Comment by gaaray2k** [comment]
Which requirements have to be met?. If I create an offering and choose the options that I want, shouldn't it just work?

**Comment by DaanHoogland** [comment]
I don't know, @gaaray2k. Obviously it is not returned by the listNetworkOfferings API. I don't know if that is because of the filtering requested or because of the options on the offering.
as you can see in http://cloudstack.apache.org/api/apidocs-4.14/apis/createNetworkOffering.html and http://cloudstack.apache.org/api/apidocs-4.14/apis/listNetworkOfferings.html there are quite a lot of options to set on -, or filter network offerings by.

**Comment by andrijapanicsb** [comment]
there networks and networks and networks and networks (isolated, shared, VPC isolated, L2) :)

Which ones are you trying to create - share a screenshot here, after configuring all the offering details (before pressing the OK/create button) (simple ctrl + v will paste an image)

**Comment by DaanHoogland** [comment]
@gaaray2k did you solve your issue? (as in can we close this?)

**Comment by DaanHoogland** [comment]
@gaaray2k closing, please reopen if needed
