### ISSUE TITLE
Egress Broken in VPC Tiers

### ISSUE THREAD

**Issue by rvalle** [apache/cloudstack#4402]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VPC
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### OS / ENVIRONMENT

Ubuntu 18.04, KVM, Advanced Networking, Local Storage

##### SUMMARY

According to the documentation: "By default, all incoming traffic to the guest networks is blocked and all outgoing traffic from guest networks is allowed, once you add an ACL rule for outgoing traffic, then only outgoing traffic specified in this ACL rule is allowed, the rest is blocked."

ACLs on VPC tiers do not block the rest of the traffic even if an Egress rule is added.

##### STEPS TO REPRODUCE

~~~
- create a VPC with 2 tiers, Management and Service
- create a custom ACL for each tier with the same name as the tier
- Create an ACL Egress rule on Management that allows accessing Service Tier (for example on port 22)
- Create a VM on Management Tier
- Test accessing the Service tier from the VM 
- Test accessing the Internet from the VM

~~~

##### EXPECTED RESULTS

~~~
The VM should have access to the Service tier as specified.
However, Since there is already an Egress rule specified the the rest of outgoing traffic should be blocked. 
The VM should not be able to access the Interenet.
~~~

##### ACTUAL RESULTS

~~~
The VM can access the internet: 
ping www.google.com works
wget http://www.google.com works.
~~~

**Comment by rvalle** [comment]
Further testing: Traffic is going out from the VPC tiers despite the 9999 deny all rule.
Something here seems fundamentally broken.

**Comment by rvalle** [comment]
I am also experiencing issues with ACLs Egress which use multiple CIDRs, although I still could not asses if the issue is with Ansible Modules or ACS. see https://github.com/ngine-io/ansible-collection-cloudstack/issues/41

**Comment by rvalle** [comment]
after discussing the multiple CIDRs issue with @resmo we think that it is related to this issue. Rules are also not working when they take multiple CIDRs as parameters.

**Comment by andrijapanicsb** [comment]
rules can't take multiple CIDRs as parameter value - please see the UI/API - at least - afaik

The original issue described here should be confirmed by someone else as well - it's a serious one IMO, even would consider it a blocked issue myself if true.

cc @Spaceman1984 @rhtyd

**Comment by rvalle** [comment]
@andrijapanicsb I check the API spec and they take a list. 

Also, Ansible modules have been built matching the API, taking lists is been tested too.

**Comment by Spaceman1984** [comment]
Tested the original issue -

I created a VPC with 3 tiers - Management, Service and NoACL - The third one had no ACL list specified.

I was able to ping google.com from VMs running on all 3 tiers. ( This is the bug )

Adding a deny rule on 0.0.0.0/0 blocked outgoing traffic.

**Comment by rvalle** [comment]
Thanks @Spaceman1984.

**Comment by andrijapanicsb** [comment]
Please see docs before confirming an issue @Spaceman1984 
http://docs.cloudstack.apache.org/en/latest/adminguide/networking/virtual_private_cloud_config.html?highlight=acl#about-network-acl-lists

Specifically:

`The default Network ACL is used when no ACL is associated. Default behavior is all the incoming traffic is blocked and outgoing traffic is allowed from the tiers...:`

With this in mind ^^^, conduct the testing... - it is expected that your noACL tier was able to ping anything outside

But the other "blocked by default..." egress issue:

I think the documentaion is not correct - i.e. for VPC networks, I don't recall that there was ever an implementation that will by default block outgoing traffic (egress) on ACLS where some Egress rules allow some access - i.e. you would always want to add 0.0.0.0/0 deny rule - it's an EMPTY ALC that you want to populate your way - just like on any other router - you will explicitely add deny to 0.0.0.0:0 as the last rule in the ACL.

I would prefer that we update the documentation on VPC ALC, instead of chaning the behaviour, unless some of you can confirm that this worked differently in previous ACS versions @rvalle ?

**Comment by rvalle** [comment]
@Spaceman1984 yes, @andrijapanicsb is right.

You can add a single egress rule to your setup, which should imply that the allow all out by default stops. then you can validate. 

@andrijapanicsb I cannot comment on previous ACS versions, I joined the party late ! 

I agree with you in which I do not like the original specification: i.e. after adding one rule the default policy changes. I don't like it. 
But I guess it would be good to know if this issue is also in pre 4.14 just in case it turns out that it works as specified in previous releases.

**Comment by DaanHoogland** [comment]
@rvalle closing this one. can you work on the description and title if you want to re-open? thanks
