### ISSUE TITLE
Support for Linstor

### ISSUE THREAD

**Issue by hstan77** [apache/cloudstack#4403]
##### ISSUE TYPE

 * Feature Idea

##### COMPONENT NAME

~~~
Storage Support for Linstor
~~~

##### CLOUDSTACK VERSION

~~~
All Version
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~
Request to support more storage type, for example, Linstor , 

I saw linstor website , seems it is support Openstack, OpenNebula, Proxmox, but too bad that Cloudstack still not there. I suggest to have support plug in for linstor
~~~

**Comment by andrijapanicsb** [comment]
Unless a specific cloudstack-user (a.k.a. some company) needs this, there are next-to-zero chances someone will implement such a huge thing "for fun".

Another option is pinging the vendor, and asking them if they want to develop ACS plugin - to broaden their eco-system.

**Comment by hstan77** [comment]
Add on of addition support to storage will increase popularity of user choose specific software to implement.  And when the popularity of software increase, hardware vendor will more willing to support for the software.

The future trend of Storage of Cloud Ecosystem is more direct to SDS, software define storage,  yet I am seeing Cloudstack SDS support is somehow  less,  Linstor is one of it, and other is such as Dell ScaleIO is not support as well.

The support of Storage in Cloudstack is a bit limited,   but I love the software, thus  I am trying to give opinion as a user point of view,  what is the thing suppose to work on to help Cloudstack gain popularity out there.

Functionality and Usability is almost there and I would say is stable and production ready.  However Storage support is kind of weak here.

**Comment by andrijapanicsb** [comment]
I'm just sharing how it really works, in practice :) 
I can tell you most users use stable, proven, 20y old technologies, like iSCSI, NFS
Some are on Ceph, some on SolidFire
I'm talking about BIG users.

Every addition is most welcome, but that usualy needs to be done by investing many hours (which, let's face it, translates to many $$$ since time=money)

If you have someone at Linstore, let him join user@ mailing list and ping us - I can tell you this is how it happened i.e. with SolidFire - one BIG user wanted to use SolidFire, so SolidFire engaged in developing a plugin for ACS   - i.e. the vendor got engaged (since selling storage product = $$$$$$$ for the vendor,vendor choosen to write the storage plugin for SolidFire)

btw, scaleIO doesn't exist any more (wink, wink)- it's now "PowerFlex " and it's coming to 4.15, stay tuned ;)
