### ISSUE TITLE
restore vm does not attach back data disks 

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#4462]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### SUMMARY

data disks are left detached

##### STEPS TO REPRODUCE

~~~
Steps: 1. Create a VM with at least 1 volume
2. Destroy the VM without expunging anything
3. Restore the VM

Observe the VM is being restored with it's root disk only, the data disk(s) are being left aside
~~~

##### EXPECTED RESULTS

~~~
One should expect if a vm is restored, then it should end up in the same state as when it was deleted 
~~~

##### ACTUAL RESULTS

~~~
VM has only root disk no data disks attached
~~~

**Comment by DaanHoogland** [comment]
@borisstoyanov any idea if this is a regression or a 'missing feature'?

**Comment by weizhouapache** [comment]
@borisstoyanov 
I tested with 4.14 and cannot reproduce the issue.
what env do you use ?

**Comment by DaanHoogland** [comment]
@weizhouapache that would answer my question, @borisstoyanov reported 4.15 (master)

**Comment by borisstoyanov** [comment]
Sounds to me as a bug to the restore functionality. Further if @weizhouapache cannot reproduce in 4.14 maybe it's a regerssion, since I've tested with latest Master.

**Comment by rhtyd** [comment]
@harikrishna-patnala @nvazquez any comments?

**Comment by weizhouapache** [comment]
> Sounds to me as a bug to the restore functionality. Further if @weizhouapache cannot reproduce in 4.14 maybe it's a regerssion, since I've tested with latest Master.

@borisstoyanov might it be caused by #4307 ? 
it has huge changes

**Comment by harikrishna-patnala** [comment]
Seems like a regression to me based on the changes made in destroy VM workflow in VMware. I'll verify and come back with a fix.

**Comment by PaulAngus** [comment]
@harikrishna-patnala 

I'm not following the logic of what you're trying to achieve here.

If a user deletes a VM which has data disks (without expunging) then the disks get detached - as expected.
Disks are seen as first-class citizens; they can be attached to a VM, but they do not **_belong_** to a VM.

Therefore, at best a warning in the UI that the disks will be detached and will have to be re-attached to be used again is the most that could be required.

Restoring a VM is a fix for deleting something that you didn't mean to; so if:

A user has deleted their VM, then attaches the disks to another VM - which (because of above) is very likely (as otherwise, they would have deleted the data disks as well). Then they realise that they need the old VM back for some reason maybe get a config off it, - how are the disk(s) going to be reattached without breaking the second VM?

so right now I'm -1 on the PR and its premise.

**Comment by vladimirpetrov** [comment]
My tests confirm that PR #4493 fixes this issue.

**Comment by andrijapanicsb** [comment]
Was this tested to NOT be happening on VMware + 4.14? - so that we can see something is / is not different now in 4.15.

I also do recall that when VM is destroyed that disks are detached - this is an old behaviour for ages.

**Comment by andrijapanicsb** [comment]
I guess I can answer my own questions - in 4.14/vmware disk are NOT detached on VM destroy, but they are on expunge.

From the functional point of view, that is LGTM - you are reverting back to the old behaviour, as in 4.14
From the PR4307 (and that is a complex one....) point of view - can you guarantee that this revert doesn't break anything now (is the gain worth the risk - this is the question)?

**Comment by harikrishna-patnala** [comment]
This will not harm or break anything as we are not reverting the detach operations but moving the detach operations from destroy workflow to expunge workflow. I'll kick off test matrix on the PR.

**Comment by rhtyd** [comment]
Fixed https://github.com/apache/cloudstack/pull/4493

**Comment by rhtyd** [comment]
New improvement issue https://github.com/apache/cloudstack/issues/4902
