### ISSUE TITLE
IPv6 Implementation

### ISSUE THREAD

**Issue by hstan77** [apache/cloudstack#4560]
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

After deep consideration , I would like to suggest to split IPv6 configuration out from current configuration page during network creation.

This means, when create network, you can choose either IPv4 network or IPv6 network,.  When create Compute offering you can choose if this offering contain IPv4 or  IPv6 network,   If you can create the IPv4 only , create instances time, you can only choose the IP from IPv4, while if you choose both IPv4 and IPv6,  create instances time, you can choose one ip from IPv4 pool and another IP from IPv6.   this type of design also allow an instance to have only IPv6 only IP while not necessary to have IPv4 in the instances.

This type of design also allow the assignment of IPv6 subnet to one Instance, instead of IPv6 Address only.

I suggest this kind of design for more flexible Cloudstack network, and to cater for the growing of IPv6 implementation .

~~~
~~~

##### CLOUDSTACK VERSION

~~~
All Version
~~~

##### SUMMARY

To have more flexible IPv6 Network Assginment.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
@wido @GabrielBrascher can you guys comment?

**Comment by rhtyd** [comment]
IPv6 discussion started here: https://markmail.org/message/23ttvzwmzuanlkyg

**Comment by rohityadavcloud** [comment]
Since last two years, we've had some rounds of ipv6 implementation and now cloudstack supports ipv6 with static routing shipped with v4.17 https://cwiki.apache.org/confluence/display/CLOUDSTACK/IPv6+Support+in+Isolated+Network+and+VPC+with+Static+Routing

https://github.com/apache/cloudstack/pulls?q=is%3Apr+ipv6+is%3Aclosed

Pl re-open or create new ticket to track new requests, thanks.
