### ISSUE TITLE
SSVM issue with 4.15 templates

### ISSUE THREAD

**Issue by AlexanderKgr** [apache/cloudstack#4579]
ssvm agent state does not change to up.

![image](https://user-images.githubusercontent.com/25532758/104276845-5b6f5e00-54ae-11eb-854c-7b1f4b4cf5d7.png)

Running health check 

![image](https://user-images.githubusercontent.com/25532758/104276721-22cf8480-54ae-11eb-8a79-f51c02d2c24e.png)

logs from cloud.log

![image](https://user-images.githubusercontent.com/25532758/104276779-3aa70880-54ae-11eb-8d4f-4a3b9c8db11e.png)

with 4.14 template never had issue.

hypervisor running xcp-ng 8.2

**Comment by AlexanderKgr** [comment]
so...using cloudstack-management from 
http://download.cloudstack.org/ubuntu/dists/bionic/4.15/ 
(which has issue with new ui)

![image](https://user-images.githubusercontent.com/25532758/104284049-16e9bf80-54ba-11eb-9cab-164f42ee9534.png)

using cloudstack-management from 

http://packages.shapeblue.com/cloudstack/upstream/debian/4.15/
and i have the above issue

**Comment by rhtyd** [comment]
@AlexanderKgr we don't officially support XCP-ng 8.2 yet with 4.15.0.0 release but I suspect the issue is to wrong patching of systemvm.iso xcpng hosts. The systemvm.iso file contains noredist jars which will include hte missing class. Since you've changed the pkgs you'll need to manually sync/scp the new systemvm.iso file from /usr/share/cloudstack-common/vms/ to the xcp ng hosts's /opt/xensource/... path (find/check and replace). Then destroy old ssvm/cpvm and try again.

**Comment by AlexanderKgr** [comment]
thanks for answering.
lost in details. do you have any guide to follow?

**Comment by AlexanderKgr** [comment]
thanks followed for instructions and fixed it
