### ISSUE TITLE
New marvin tests service

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#4799]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
UI, marvin tests
~~~

##### CLOUDSTACK VERSION
~~~
4.16
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Currently it is possible to execute integration/smoke/component tests for CloudStack through an external Python executor using marvin and nosetests. The test runner can be invoked on a CloudStack management server or in a dedicated server for the tests runner. The tests execution is decoupled from the CloudStack management server and requires further work to explore/display results.

It would be nice to integrate both sides to help administrators to easily start these tests and check their results on the UI. Also, the administrator would select which tests to run, update/add test data, etc.

The CloudStack management server could communicate with a new service in charge of receiving the parameters passed by the administrator and invoke the tests. This new service will also be reporting/sending updates on the progress of the tests execution to the management server, so the information can be displayed in the UI.

**Comment by rhtyd** [comment]
@nvazquez can you use the structure/format as in https://github.com/apache/cloudstack/issues/4696

**Comment by weizhouapache** [comment]
@nvazquez good.
I do not know if administrators are interested in it, but it will help cloudstack developers a lot !

**Comment by DaanHoogland** [comment]
Nota Bene: a lot of tests leave garbage around, I've done a lot of cleanup during python3 migration of marvin tests, but it is far from clean now.

**Comment by ravening** [comment]
One thing that comes to my mind is to use the frontail package which displays the tail -f output of a file on UI.

Also since it can be run on dedicated server, it's better to separate out this service from Cloudstack MGT server.

I would say do below steps

Have a separate service which exposes REST API's to get list of test, executing all test and individual test and so on. Once API is executed, it displays the execution output on UI.

Since it can be a standalone service, we can have a list of IP address of the machines where this service is running and select a particular machine based on user input. So we can have all test environment in just one UI

**Comment by sureshanaparti** [comment]
this service should also facilitate parallel execution of independent tests (in the same Cloudstack env) whenever possible. If this service is separated from MGMT server (as said above), how about getting and executing tests (at the same time) of multiple Cloudstack environments.

**Comment by rohityadavcloud** [comment]
Closing this, we'll explore the ideas as other tickets. I don't see this as a student project. Thanks for sharing @nvazquez
