### ISSUE TITLE
Backup usages are still generated after VM deletion

### ISSUE THREAD

**Issue by olivierlemasle** [apache/cloudstack#4990]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
Usage
~~~

##### CLOUDSTACK VERSION
~~~
4.14.1.0
4.15.0.0
~~~

##### CONFIGURATION
Backup framework enabled

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When a VM is assigned to a backup offering, deleting the VM do not stop the generation of backup usages.

##### STEPS TO REPRODUCE

~~~
1. Deploy a VM
2. Assign the VM to a backup offering
3. Ensure at least one backup is created
4. Delete the VM
~~~

##### EXPECTED RESULTS

~~~
The usage records for backups (usage type 28) should stop when the VM is destroyed.
~~~

##### ACTUAL RESULTS

~~~
Backup usage records are generated indefinitely.
~~~

**Comment by rhtyd** [comment]
@olivierlemasle in your test did you delete the backup as well?

**Comment by olivierlemasle** [comment]
@rhtyd  Yes, I deleted the backups as well (but after the VM deletion),  and the usage service continued to generate new usages (because it only stops when an event `BACKUP.OFFERING.REMOVE` occurs, which will _never_ occur since the VM is deleted).

**Comment by rhtyd** [comment]
Okay @olivierlemasle - if usage records are not marked on deletion of backups - that's indeed a bug.

**Comment by rhtyd** [comment]
Fixed in https://github.com/apache/cloudstack/pull/5017 
@olivierlemasle we concluded the fix is not necessary for this bug, which is expected - we should continue billing until all backups are removed. The issue fixed in the PR is (a) remove VM from backup offering when VM is expunged and no backups exist, (b) remove VM from backup offering when there is only 1 backup which is deleted.
