### ISSUE TITLE
Fail to delete volume left after template removed

### ISSUE THREAD

**Issue by levindecaro** [apache/cloudstack#5088]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Volumes Management
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### OS / ENVIRONMENT

CentOS 7.9
KVM

##### STEPS TO REPRODUCE

~~~
1. Create a snapshot from existing instance
2. Create a template from the snapshot
3. Deploy a new instance from the template
4. Remove the new instance
5. Delete the template from zone
6. A ROOT volume left by "Destroy" status
7. Delete the volume



~~~

##### EXPECTED RESULTS

~~~
The volume shall be expunged. 
~~~

##### ACTUAL RESULTS

~~~
Delete the volume but report error., the volume stay in "Destroy" status forever. Filesystem remains the volume file.

Request Failed (431)
Please specify a volume that is not attached to any VM.

Jun 09 12:32:35 cloudstack-1[109793]: INFO  [c.c.a.ApiServer] (qtp1965237677-1278:ctx-82e0da3a ctx-550fe484) (logid:2a2c5dec) Please specify a volume that is not attached to any VM.

~~~

**Comment by rhtyd** [comment]
@levindecaro how long did you wait for the expunge event to complete? See the expunge.delay and expunge.interval settings. 
@shwstppr @Pearl1594 can we reproduce it?

**Comment by levindecaro** [comment]
@rhtyd 

The expunge.interval  is 86400, I was wait for days before report this issue. Thank you.

**Comment by Pearl1594** [comment]
If the VM was destroyed (not expunged) and an attempt was made to the delete the volume before the expunge interval has elapsed - then yes, deletion of volume fails with the mentioned error. I believe this would be the expected behavior. I tried the above steps and attempted deleting the Volume of a destroyed VM, while it did throw the exception, it did not transition the volume to destroy state; and after the expunge interval / delay the volume gets automatically deleted.
@levindecaro  Is this consistently happening for all volumes? Would it be possible for you to reduce the expunge.delay and expunge.interval to a few seconds and see if the deletion of volume fails when the expunge job automatically kicks in. If yes, can you please share the logs. Thanks

**Comment by levindecaro** [comment]
@Pearl1594

Thanks for your explanation. I'm trying to reproduce this state status issue and sorted out the user was delete the instance without select "expunge" during deletion. So the instance was deleted and the disk image left by "Destroy" status.

In this scenario,
1. If try to delete it, it report "Request Failed (431) Please specify a volume that is not attached to any VM."
2. If try to recover it, it will associate the VM name where it was deleted before.
3. Click on the VM name, it will be 404
4. Click on the ROOT disk volume, it has "Snapshot", "Recurring Snapshots", "Resize" option, no way to delete it any way.


Refining the step reproduce as below.
```
1. Create a snapshot from existing instance
2. Create a template from the snapshot
3. Deploy a new instance from the template
4. Remove the new instance (without expunge) 
5. Delete the template from zone
6. A ROOT volume left by "Destroy" status
7. Delete the volume, error raised.
8. Recover the volume, cannot delete as well.

```

**Comment by Pearl1594** [comment]
@levindecaro  Are there any error logs that you see when the volume goes into 'Destroy' state when the VM is destroyed. While I am unable to reproduce the issue following the mentioned steps at my end, the logs may provide some insight as to why that may be happening. 
When I attempt to destroy the VM (without expunge) the volumes remains in Ready state and then gets expunged after the expunge interval / delay.

![image](https://user-images.githubusercontent.com/10495417/121390463-07887880-c96b-11eb-8ec4-9d1152473cb8.png)

**Comment by levindecaro** [comment]
I just got this logs during deletion, but it dont looks meaningful.

```
2021-06-10 01:57:07,668 DEBUG [c.c.a.ApiServer] (qtp1965237677-397:ctx-1ed42423 ctx-5e982d78) (logid:34d356ec) CIDRs from which account 'Acct[d09266b9-4e22-40b8-a013-da17fc4a3cac-levin.ng]' is allowed to perform API calls: 0.0.0.0/0,::/0
2021-06-10 01:57:07,690 DEBUG [c.c.u.AccountManagerImpl] (qtp1965237677-397:ctx-1ed42423 ctx-5e982d78) (logid:34d356ec) Access to Acct[d09266b9-4e22-40b8-a013-da17fc4a3cac-levin.ng] granted to Acct[d09266b9-4e22-40b8-a013-da17fc4a3cac-levin.ng] by DomainChecker
2021-06-10 01:57:07,694 DEBUG [c.c.u.AccountManagerImpl] (qtp1965237677-397:ctx-1ed42423 ctx-5e982d78) (logid:34d356ec) Access to Vol[1824|vm=1541|ROOT] granted to Acct[d09266b9-4e22-40b8-a013-da17fc4a3cac-levin.ng] by DomainChecker
2021-06-10 01:57:07,909 INFO  [c.c.a.ApiServer] (qtp1965237677-397:ctx-1ed42423 ctx-5e982d78) (logid:34d356ec) Please specify a volume that is not attached to any VM.
2021-06-10 01:57:07,909 DEBUG [c.c.a.ApiServlet] (qtp1965237677-397:ctx-1ed42423 ctx-5e982d78) (logid:34d356ec) ===END===  172.16.2.198 -- GET  id=1fab69ea-864c-4dac-b51f-f5bdd45685ba&command=deleteVolume&response=json
```


Now I got one is recovered and one is state destroy, both cannot delete

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/36956864/121405871-1f262800-c990-11eb-8d46-9469caa2f2da.png">


<img width="1017" alt="image" src="https://user-images.githubusercontent.com/36956864/121406030-48df4f00-c990-11eb-9564-be878f0643ce.png">

"test-template" template are already deleted.

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/36956864/121406093-585e9800-c990-11eb-8aad-f12403a96739.png">

Both "test-tempalte-2-new" VM and "test-template2" Template are already deleted 
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/36956864/121406153-68767780-c990-11eb-9128-99b3fa07ee31.png">

**Comment by Pearl1594** [comment]
The actual issue here seems to be that the volume gets stuck in "destroy" state. @levindecaro Can you please let us know when exactly the volume's state gets set to "destroy". As the actual volume lifecycle is as follows:
1. When VM is destroyed - VM enters "Destroyed" state but volume is still in "Ready" state
2. When VM gets cleaned up i.e., expunged - the volume enters destroy state and then gets expunged - destroy would just be an intermediary state
Could you try:
- expunging the VM and seeing if the root volume of the VM doesn't get expunged i.e., still gets stuck in destroyed state
- destroy the VM and then do an expunge operation and verify the same
It would be helpful to get this information as I wasn't able to reproduce it.

**Comment by rhtyd** [comment]
@levindecaro are you using Ceph or NFS or something else?
@weizhouapache @wido @GabrielBrascher are you finding this in ceph env?

**Comment by weizhouapache** [comment]
@levindecaro @Pearl1594 
I was not able to reproduce the issue either. the volume is "Ready" state at the end of my testing.

**Comment by levindecaro** [comment]
@rhtyd 

I restarted ACS management server last night and found the "Destroy" status volumes are successfully purged. Afterwards I patch the "Recover->Ready" state volume to "Destroy" in DB, and found that it do expunged as well after the defined interval. So I do think there maybe stuck thread happening before restart, however, I could not found any logs that indicate this situation. I'd like to close this issue for now. Thank you for all.
