### ISSUE TITLE
”cpu.overprovisioning.factor“ Configuration not in effect

### ISSUE THREAD

**Issue by staySober** [apache/cloudstack#5185]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
 cloudstack-managemnt server
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1-SNAPSHOT
~~~

##### STEPS TO REPRODUCE

~~~
change `cpu.overprovisioning.factor ` value to 2，But it doesn't work 
~~~
![image](https://user-images.githubusercontent.com/20500978/124564815-0405e580-de74-11eb-8c15-82c544bd8bda.png)

##### EXPECTED RESULTS

~~~

cpu.overprovisioning.factor  can be configured correctly

~~~

##### ACTUAL RESULTS

~~~
it doesn't work correctly. 
~~~
![image](https://user-images.githubusercontent.com/20500978/124565383-8ee6e000-de74-11eb-8d5a-676d03eff1c1.png)

**Comment by slavkap** [comment]
@staySober, I've tested this, and `cpu.overprovisioning.factor` is set correctly. This is just a warning that the configuration wasn't found in `Config.java` because it's deprecated and most of the configurations are moved to ConfigDepot. If it wasn't in ConfigDepot you will get something like this `Did not find configuration cpu.overprovisioning.factor in ConfigDepot too.`
I've changed the value to 2 and created a new cluster that takes the new value

![image](https://user-images.githubusercontent.com/51903378/124571807-cc397680-de50-11eb-9bd1-a8faedd5090e.png)


![image](https://user-images.githubusercontent.com/51903378/124571899-dd828300-de50-11eb-9c34-58f16222f786.png)

or you mean about something else

**Comment by staySober** [comment]
@slavkap  but when I deploy a VM, I saw the log as follow
![image](https://user-images.githubusercontent.com/20500978/124573563-3e738080-de7c-11eb-8e9a-71b40c8c1910.png)
I think it's mean My cpu.overprovisioning.factor is value '1', but I set it value to `2`

**Comment by slavkap** [comment]
Hmm not sure what steps you've taken. To take effect on old hosts, you have to update the `cpu.overprovisioning.factor` in the cluster's settings. If you changed it from the `Global Settings` tab, it will take effect only on newly created clusters (maybe I'm wrong, but I came to this conclusion after a quick check of the code )

**Comment by staySober** [comment]
@slavkap Oh, My problem. I forget check the cluster setting. now It work correctly. Thanks for your help me.
