### ISSUE TITLE
Does the basice network modle can handle the problem?

### ISSUE THREAD

**Issue by xuanyuanaosheng** [apache/cloudstack#5198]
##### ISSUE TYPE

 * Other

We use CloudStack in our company. 
I have some question:

1.  we use The Basic Network mode in same cluster, can we use different VLAN for MGMT traffic and Guest Traffic? 
     For example: the manager network is  vlan 136 and the guest network is vlan 291.
      
    
![image](https://user-images.githubusercontent.com/4197714/125224879-eff13680-e300-11eb-9250-a0519e1d0027.png)

      

2.  We would like the guest server in  cloudstack could communicate with other Non-cloudstack servers directly in vcenter without NAT, any suggestion about this?

3.   The cloudstack  agent host network configuration is must config in advanced or just config in cloudstack web when add zone ? 
http://docs.cloudstack.apache.org/projects/archived-cloudstack-installation/zh_CN/latest/hypervisor/kvm.html#network-example-for-basic-networks
http://docs.cloudstack.apache.org/projects/archived-cloudstack-installation/zh_CN/latest/hypervisor/kvm.html#configuring-the-network-bridges-for-advanced-networks

**Comment by DaanHoogland** [comment]
@GabrielBrascher @wido Do you know the answer to this?

**Comment by wido** [comment]
No, this is not possible. Basic networking allows only one VLAN per POD.

You have to define cloudbr0 for this which you can map to any VLAN on your Linux host.

**Comment by xuanyuanaosheng** [comment]
@wido Thank you for your reply.  

The first question: there is only one vlan in the basic zone type.
![image](https://user-images.githubusercontent.com/4197714/125547228-92ae630b-b872-4b8f-b1de-6d99eb56616f.png)

**Comment by xuanyuanaosheng** [comment]
@wido   I can not install _bridge-utils_ in oracle 8, Does this affect the add of agent host ?

**Comment by GabrielBrascher** [comment]
@xuanyuanaosheng I think that the main requirement is just in order to have the bridges configured. If you configure bridges without _bridge-utils_ I don't see any problem.

As an example of this, we can notice that the CentOS 7 packaging has the _bridge-utils_ as a requirement (see: [packaging/centos7/cloud.spec](https://github.com/apache/cloudstack/blob/9678c7bd1e0cb6b4fa53b8bbef75d50d8d6812f6/packaging/centos7/cloud.spec#L109)); however, CentOS 8 ([packaging/centos8/cloud.spec](https://github.com/apache/cloudstack/blob/9678c7bd1e0cb6b4fa53b8bbef75d50d8d6812f6/packaging/centos8/cloud.spec#L98)) does not share the same requirements.

Thus, I assume that it would not affect your host with oracle 8 as long as keeping the bridges set up on the KVM nodes following the CloudStack documentation.

**Comment by xuanyuanaosheng** [comment]
@GabrielBrascher  Thank you for your reply.  I know.

**Comment by rhtyd** [comment]
@xuanyuanaosheng I've not checked all the details you've shared, but you may want to test with an advanced zone and create a shared network in it for more flexibility for VLAN configuration/management. Security groups may also be used/tested.

**Comment by xuanyuanaosheng** [comment]
@rohityadavcloud @GabrielBrascher @wido Thanks for your help. I will close this issue.

The related issue is : https://github.com/apache/cloudstack/issues/5462
