### ISSUE TITLE
UI - As User - Broadcast URI column available to user, but blank

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#5596]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### SUMMARY

As User, at the networks page the table contains Broadcast URI field, but the user does not have access to the values through API. It would be good if the UI would crop the columns when that are not available/have values. Open for discussions.

**Comment by rhtyd** [comment]
Since this is good to have, not exposing any data - moved to 4.16.1.0. Generally it's a good idea that except root-admin users aren't aware of their vlans, I'm not sure about other isolation methods. Maybe for some non-VLAN isolation method, exposing broadcase URI makes sense. This can be checked what we set/return in API at the backend, and if we don't for any case then simply hide/remove the column by checking user role type.

**Comment by DaanHoogland** [comment]
we will have to decide to show or not show. In a mixed environment, i.e. with multiple isolation methods, we will end up with a mix of networks, some requiring the user to see the broadcast uri and other forbidding it.
I suggest a setting allowing the operator to control it @rhtyd ?

**Comment by weizhouapache** [comment]
The URI should not be visible for non-root users.

**Comment by sureshanaparti** [comment]
Verified the fix in PR #5745.

@borisstoyanov Closing this issue as the fix PR is merged. Reopen it if you still see this issue. Thanks.
