### ISSUE TITLE
regular user has no access to offferings for creating a new volume

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#6013]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI, Storage, Orchestration
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~
login as a regular user,
go to storage -> volumes
click "Create Volume"
~~~

##### EXPECTED RESULTS

~~~
have a choice of offerings, like admin gets
~~~
![image](https://user-images.githubusercontent.com/2486961/154922215-996017aa-173c-4f4d-a2bb-e4a134261022.png)

##### ACTUAL RESULTS

~~~
no offerings, hance no possibility to create volumes
~~~
![image](https://user-images.githubusercontent.com/2486961/154922063-484278b0-5248-4dcd-9612-c6baa9f4e77a.png)

**Comment by weizhouapache** [comment]
hmm
this looks like a blocker issue

api does not work either
```
(localcloud) SBCM5> > list diskofferings 
🙈 Error: (HTTP 530, error code 4250) Internal error executing command, please contact your system administrator
```

**Comment by weizhouapache** [comment]
@DaanHoogland 
this seems to be another regression of #5008

**Comment by DaanHoogland** [comment]
I can confirm it works in 4.16.1 RC

**Comment by harikrishna-patnala** [comment]
DB query on diskoffering view failed.
com.cloud.utils.exception.CloudRuntimeException: Caught: com.mysql.cj.jdbc.ClientPreparedStatement: SELECT disk_offering_view.id, disk_offering_view.uuid, disk_offering_view.name, disk_offering_view.display_text, disk_offering_view.provisioning_type, disk_offering_view.disk_size, disk_offering_view.tags, disk_offering_view.use_local_storage, disk_offering_view.customized, disk_offering_view.customized_iops, disk_offering_view.min_iops, disk_offering_view.max_iops, disk_offering_view.hv_ss_reserve, disk_offering_view.sort_key, disk_offering_view.bytes_read_rate, disk_offering_view.bytes_read_rate_max, disk_offering_view.bytes_read_rate_max_length, disk_offering_view.bytes_write_rate, disk_offering_view.bytes_write_rate_max, disk_offering_view.bytes_write_rate_max_length, disk_offering_view.iops_read_rate, disk_offering_view.iops_read_rate_max, disk_offering_view.iops_read_rate_max_length, disk_offering_view.iops_write_rate, disk_offering_view.iops_write_rate_max, disk_offering_view.iops_write_rate_max_length, disk_offering_view.cache_mode, disk_offering_view.compute_only, disk_offering_view.created, disk_offering_view.removed, disk_offering_view.domain_id, disk_offering_view.domain_uuid, disk_offering_view.domain_name, disk_offering_view.domain_path, disk_offering_view.zone_id, disk_offering_view.zone_uuid, disk_offering_view.zone_name, disk_offering_view.display_offering, disk_offering_view.state, disk_offering_view.vsphere_storage_policy, disk_offering_view.disk_size_strictness FROM disk_offering_view WHERE disk_offering_view.compute_only = 0  AND  AND  ( FIND_IN_SET(** NOT SPECIFIED **, disk_offering_view.zone_id )  OR disk_offering_view.zone_id IS NULL )  AND  (disk_offering_view.domain_id IS NULL )  AND disk_offering_view.removed IS NULL  ORDER BY disk_offering_view.sort_key ASC , disk_offering_view.id ASC  LIMIT 0, 500

Looking for the root cause.

**Comment by harikrishna-patnala** [comment]
Created a PR to fix the issue https://github.com/apache/cloudstack/pull/6015, please review
