### ISSUE TITLE
GSoC 2022 Idea: CloudStack Terraform Provider - Add support for Kubernetes Clusters

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack#6040]
## Background

Terraform is an Infrastructure as Code (IaC) software that provides a consistent CLI workflow to manage resources in
many cloud services. Cloudstack Terraform provider integrates with Cloudstack to aid in managing and automating the deployment of resources in cloudstack. We have recently made the first release of CloudStack Terraform Provider v0.4.0 https://github.com/apache/cloudstack-terraform-provider

The CloudStack Kubernetes Service (CKS) is CloudStack's own managed Kubernetes offering which gives users a completely managed Kubernetes cluster with just the click of a few buttons within their existing IaaS environments

As of now the CloudStack Terraform Provider does not support managing CKS clusters

## Requirement

This proposal aims to add support to the CloudStack Terraform Provider to manage CKS clusters

This would involve supporting the following actions on CKS clusters :
- Create
- Stop / Start
- Scale
- Upgrade
- Delete

#### [Optional]
Support the following actions on the binary ISOs :
- Register
- Enable / Disable
- Delete

## Relevant Skills
- GoLang

## Difficulty
Medium

## Duration
175 hours

## Potential Mentors
- Harikrishna Patnala
- David Jumani

## References
- https://registry.terraform.io/providers/cloudstack/cloudstack/latest/docs/
- https://cloudstack.apache.org/api/apidocs-4.16/

**Comment by harikrishna-patnala** [comment]
Following will be the resources and their operations that need to be added to CloudStack Terraform Provider.

1. Kubernetes cluster - CRUD operations, Start/Stop, Scale, Upgrade
2. Kubernetes supported version - CRUD operations

Please check the APIs under "Kubernetes Service" https://cloudstack.apache.org/api/apidocs-4.16/

**Comment by Damans227** [comment]
Hi @davidjumani @harikrishna-patnala I hope you are doing well. 

I have drafted a design document for this issue, and would appreciate if you could provide me some feedback. I have allowed your email address to access the design document saved as a google doc at the link below: 

https://docs.google.com/document/d/16KHE2hy75JGE2bEQIYwjkEk0vHoJa-bC/edit?usp=sharing&ouid=109681619309347919886&rtpof=true&sd=true

I am an open source enthusiast and a graduate student working towards masters in engineering at Carleton University in Ottawa. I believe I have the right credentials and enough time to complete this project as part of GSoC2022. I am an existing [CloudStack Commite](https://github.com/apache/cloudstack/pulls?q=+is%3Apr+author%3ADamans227+)r, Kubernetes Organization member working on the [Sig-Release](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.22/release-team.md), and a [Certified Kubernetes Administrator](https://www.credly.com/badges/57c437b3-d998-4d97-9276-1f968c39b883/public_url). 

I started contributing to CloudStack last year, and have been doing frequent mechanical changes in the VueJS based frontend since then. I have had the honour of meeting a few contributors and maintainers of the CloudStack project at last year's CloudStack Collaboration Conference, and I plan on showcasing my work in the CloudStack Community at the same conference this year. 

I am passionate about the CloudStack project and have been ramping up my knowledge gradually since I got involved. If I get a chance to work on this project, I assure you I will give my best and fulfil all my commitment towards the project on time. 

Looking forward to hearing from you. 

cc: @borisstoyanov @rohityadavcloud

**Comment by harikrishna-patnala** [comment]
Thanks @Damans227, great to see your draft, looks good. I've added a few comments, can you please check and update the document accordingly. Please feel free to comment back if you have any points to discuss.

**Comment by Damans227** [comment]
> Thanks @Damans227, great to see your draft, looks good. I've added a few comments, can you please check and update the document accordingly. Please feel free to comment back if you have any points to discuss.

Thanks for your feedback Harikrishna. Appreciate it. 

Your comments are very helpful. I will update the document accordingly and let you know very shortly.

**Comment by Damans227** [comment]
@harikrishna-patnala Hi! I have changed the design document as per your comments. So, when you get a chance, please revisit the Purpose and the Sample Implementation section and provide your feedback. Thx!

**Comment by harikrishna-patnala** [comment]
Thanks for the changes @Damans227, looks good to me.

**Comment by Damans227** [comment]
> Thanks for the changes @Damans227, looks good to me. 

Alright, many thanks for your feedback.

**Comment by Damans227** [comment]
@harikrishna-patnala @davidjumani @borisroman Hi Guys, I hope you are doing well. I have submitted a project proposal for this issue today, PTAL. Thanks!

**Comment by borisstoyanov** [comment]
Thanks @Damans227, we'll have @davidjumani and @harikrishna-patnala review your submission and get back to you if needed.

**Comment by rohityadavcloud** [comment]
Thanks for submitting the idea, GSoC2022 has ended. I'm closing this, you can resubmit this idea again for next year in case this wasn't selected or worked upon this year.
