### ISSUE TITLE
Cleanup: Remove redundant API to change service offering for VMs

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#6150]
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
API
~~~

##### CLOUDSTACK VERSION
~~~
4.17.0-SNAPSHOT and above
~~~

##### OS / ENVIRONMENT
N/A

##### SUMMARY
As investigated on #3110, PR #5008 had impact on two similar APIs for changing the service offering for a VM, resulting both on resizing the VM's ROOT volume (`scaleVirtualMachine` and `changeServiceForVirtualMachine` APIs)

The proposal is to remove the `changeServiceForVirtualMachine` API, since it is not used in the UI codebase, and the outcome of this API can be obtained by invoking `scaleVirtualMachine`.

**Comment by harikrishna-patnala** [comment]
Agree @nvazquez we can remove the API "changeServiceForVirtualMachine" since "scaleVirtualMachine" handles both stopped and running VM to change the offering.

@DaanHoogland @sureshanaparti a quick suggestion is needed here please. Can I proceed with completely removing the API or using deprecate annotations? My only concern with deprecate annotation is I did not see any proper notification on deprecation when the API is used, so users may end up using it even after the deprecation.

**Comment by DaanHoogland** [comment]
@harikrishna-patnala for an API we can only annotate it and not prevent any usage of it. We should wait with removing it untill 5.0 if at all it comes. If `scaleVirtualMachine` allows for changing the service offering than we can mark `changeServiceForVirtualMachine` for removal and maybe cripple its functionality. We have more clients than the UI hwoever, so let's not remove it just yet (cmk, terraform, ...).

**Comment by GabrielBrascher** [comment]
Agree with removing it. But also agree with @DaanHoogland. Removing it would cause API backwards compatibility and therefore requires a 5.0 (which would be fine for me).

For a 4.X.Y we can deprecate it adding an annotation and also spreading the words via release notes, documentation etc.

**Comment by harikrishna-patnala** [comment]
Thanks guys, I've raised a PR, please review.

**Comment by rohityadavcloud** [comment]
Fixed in https://github.com/apache/cloudstack/pull/6540
