### ISSUE TITLE
Template - Dynamically Scalable toggle button in Edit window doesn't reflect the actual value

### ISSUE THREAD

**Issue by hc7244** [apache/cloudstack#6295]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
UI
~~~

~~~

##### CLOUDSTACK VERSION
4.16

~~~

~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY

If a template shows a Dynamically Scalable value of true, the Dynamically Scalable toggle button is off when you go to the Edit option.

##### STEPS TO REPRODUCE

I used packer to create a new CloudStack template.  In my source, I set template_scalable=true.  When I look at the Details of the template in the UI, Dynamically Scalable is showing true, as it should.  However, if I click on the Edit link, the Dynamically Scalable toggle is turned off.  It should be in the On position.  I clicked it to On and clicked OK.  In the Details, Dynamically Scalable still shows true; however, if I go back into Edit, the Dynamically Scalable toggle is off again.

~~~

~~~

##### EXPECTED RESULTS

The template's Dynamically Scalable toggle button in the Edit window should reflect the correct value.  "true" means the toggle button should be on.
~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by Pearl1594** [comment]
@hc7244 thanks for reporting . This seems to be fixed in the main branch (4.17) - i.e., when the details show that the template is dynamically Scalable, the edit Template form has the switch in the On position:
![image](https://user-images.githubusercontent.com/10495417/164396989-90d98e87-0085-4be6-b36e-8d1383cae5b7.png)

![image](https://user-images.githubusercontent.com/10495417/164396725-b30538c1-1f1f-4e00-8335-cf1f67fbfa4f.png)

And on disabling it, both the details and the edit form point to the correct state of the setting:
![image](https://user-images.githubusercontent.com/10495417/164397083-790edf2d-95b0-4928-8d56-e5392386b5c2.png)
![image](https://user-images.githubusercontent.com/10495417/164397281-c1cf7c0a-8497-4e3d-907f-d900945a4412.png)
