### ISSUE TITLE
Response of GET getKubernetesClusterConfig does not match the entry in GET listApis

### ISSUE THREAD

**Issue by saffronjam** [apache/cloudstack#7425]
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
API
~~~

##### CLOUDSTACK VERSION
~~~
4.18
~~~

##### CONFIGURATION
Default configuration

##### OS / ENVIRONMENT
N/A

##### SUMMARY

The response of **GET getKubernetesClusterConfig** does not match the entry in **GET listApis**

GET getKubernetesClusterConfig returns
```
{
  "clusterconfig": {
    "id": "<uuid>"
    "name": "<cluster name>",
    "configdata": "<config data> "
  }
}
```

While
GET listApis specifies:
```
{
    "id": "<uuid>"
    "name": "<cluster name>",
    "configdata": "<config data> "
}
```

##### STEPS TO REPRODUCE
~~~
1. Run GET getKubernetesClusterConfig for some kubernetes cluster
2. Run GET listApis and check the entry for the getKubernetesClusterConfig route

It does not match
~~~

##### EXPECTED RESULTS

I expect **either** GET getKubernetesClusterConfig to return
```
{
    "id": "<uuid>"
    "name": "<cluster name>",
    "configdata": "<config data> "
}
```

**or** GET listApis include the parent struct *clusterconfig*

##### ACTUAL RESULTS
GET getKubernetesClusterConfig does not match the corresponding entry in GET listApis 

![image](https://user-images.githubusercontent.com/26722370/231158533-5810efd1-ade6-46b3-be9a-11fea26ac0e1.png)

![image](https://user-images.githubusercontent.com/26722370/231158702-b1e55ae0-74bc-44b5-a33b-1e10d91de159.png)

##### CONTEXT

This issue is related to https://github.com/apache/cloudstack-go/issues/55

cloudstack-go is generated by GET listApis and cannot parse json response right now since it does not expect the parent struct *clusterconfig*

**Comment by mlsorensen** [comment]
This actually looks to be a widespread issue with the golang client. None of the items in `listApis` return the response object name. This can be seen with other commands like `getCloudIdentifier` and `getUser`, which are also broken in the golang client.

I'd wager that any API that doesn't return a list response is broken in the golang client. Looking at the client code generation, any APIs that begin with "list" will automatically be nested in a slice using a parsed name, e.g. "listVirtualMachines" gets "list" prefix removed and made singular, and the base response key becomes "virtualmachine".

I checked three different 'get' APIs via the golang client and they all either unmarshaled to an empty struct (since the response didn't match the struct), or threw an unmarshal error.

There's no formulaic way to determine what this base key should be, for `getPathForVolume` it is `apipathforvolume`. For `getCloudIdentifier` it is `cloudidentifier`, for `getKubernetesClusterConfig ` it is `clusterconfig`.

I think we need to start by providing the response object name in `listApis`, then we can overhaul the golang client to make use of this

**Comment by weizhouapache** [comment]
this seems to be fixed by https://github.com/apache/cloudstack-go/pull/58
