### ISSUE TITLE
Can't upload iso from local

### ISSUE THREAD

**Issue by HtainL** [apache/cloudstack#7568]
while i upload ubuntu 18.04 from local i saw this error. 

![image](https://github.com/apache/cloudstack/assets/134905472/442ddc9c-5046-4564-8cd3-99b68f26b8fa)

![image](https://github.com/apache/cloudstack/assets/134905472/e17d4a23-75a2-4fae-9de3-de24f7f8ff6b)

**Comment by rohityadavcloud** [comment]
@HtainL did you setup SSL certificates for your zone/ssvms? And which version of CloudStack is that? If you're on 4.18, you can use http to upload templates by setting use.https.to.upload to false and restarting your mgmt server and ssvm.

**Comment by HtainL** [comment]
@rohityadavcloud  I didn't setup SSL and https in mgmt server. I login mgmt server with http://mgmtip:8080. 
And i can't find use.https.to.upload in /etc/cloudstack/management/server.properties

**Comment by kiranchavala** [comment]
@HtainL 

Please find global settings at this path configuration > global settings , you disable the setting and

1. Restart mgmt service 

service cloudstack-managment restart

2. Restart the ssvm


![Screenshot 2023-05-29 at 4 32 25 PM](https://github.com/apache/cloudstack/assets/1401014/fe2b79b4-b568-4705-a1a1-6eceb8a47bd3)

**Comment by HtainL** [comment]
@kiranchavala   Hello bro. I did all above step, and i still can't upload the iso from local.

**Comment by kiranchavala** [comment]
@HtainL  clear the cache of the browser or try in an incognito window

Please send the management server log if you are hitting the exception

**Comment by HtainL** [comment]
@kiranchavala  I tried that way but same error occured. I shared a link that include a management server log. Thank you so much for helping me.

https://we.tl/t-lBG5u5LmND

**Comment by thorzinaung** [comment]
@HtainL @kiranchavala i got the same error also. I did steps exactly like mention upper but still got same issue. Can give more suggestion?

**Comment by kiranchavala** [comment]
@HtainL @thorzinaung  let me cross-check internally and revert back 

What is the cloudstack version you are using ?

**Comment by thorzinaung** [comment]
@kiranchavala hi, my cloudstack version is 4.18.0.0 bhai.

**Comment by kiranchavala** [comment]
Hi @HtainL @thorzinaung 

Cloudstack supports upload iso only  via HTTPS enabled ssvm , please refer to the documentation

As a workaround, please  follow the steps 

1. Disable the global setting (use.https.to.upload ) to false

2. Restart mgmt service

service cloudstack-managment restart

3. Restart the ssvm

4. Open the dev tools in ur browser , and select upload the iso 

<img width="1419" alt="Screenshot 2023-06-01 at 6 46 01 PM" src="https://github.com/apache/cloudstack/assets/1401014/1f7ee6b9-f3a4-4d34-966d-c5207142fdc3">



5. Copy the failed  POST request and paste in a new tab and click on allow 

Ex: https://10.0.55.61/upload/ce4f681a-c08e-4062-a3ab-191797a55a8a

6. Allow the browser to trust it 

<img width="1224" alt="Screenshot 2023-06-01 at 6 47 44 PM" src="https://github.com/apache/cloudstack/assets/1401014/34498fd4-3c60-4711-8002-f9ee93a33543">

7. Try to submit the request again 

<img width="653" alt="Screenshot 2023-06-01 at 6 48 44 PM" src="https://github.com/apache/cloudstack/assets/1401014/85dd0fb4-04cb-469d-b112-1816dc463064">



If it still doesn't work i would suggest to register the iso from a webserver instead of local Iso upload

**Comment by DaanHoogland** [comment]
@HtainL  I am closing this issue. If you feel this is invalid please reopen or create a new one

**Comment by jibingl** [comment]
> [@HtainL](https://github.com/HtainL)
> 
> Please find global settings at this path configuration > global settings , you disable the setting and
> 
> 1. Restart mgmt service
> 
> service cloudstack-managment restart
> 
> 2. Restart the ssvm
> 
> ![Screenshot 2023-05-29 at 4 32 25 PM](https://github.com/apache/cloudstack/assets/1401014/fe2b79b4-b568-4705-a1a1-6eceb8a47bd3)

In my case, got the same issue on uploading ISO locally. By following above solution, I re-generate the ssvm, not just restart it. Then the issue fixed.
