### ISSUE TITLE
unable to register ISO in cloudstack

### ISSUE THREAD

**Issue by thorzinaung** [apache/cloudstack#7571]
i readded Zone in cloudstack and now i can't register ISO. Any suggesstion pls. pls see the below picture.
<img width="285" alt="image" src="https://github.com/apache/cloudstack/assets/122773216/d8a31741-5c45-419a-a48b-661b66412e67">

**Comment by kiranchavala** [comment]
@thorzinaung 

Please follow the guidelines,  when opening an issue, Mention all the relevant details so that it's easy for the community members to understand the issue 

##### ISSUE TYPE
##### COMPONENT NAME
##### CLOUDSTACK VERSION
##### CONFIGURATION
##### OS / ENVIRONMENT
##### SUMMARY
##### STEPS TO REPRODUCE
##### ACTUAL RESULTS


Could you please cross-check if the Infrastructure > System vm's are running?


![Screenshot](https://github.com/apache/cloudstack/assets/1401014/cff71184-6e38-404d-8e0e-07a779fc0c01)

**Comment by thorzinaung** [comment]
@kiranchavala yes. sorry for inappropriate bhai. i'm new here. i will careful next time. it's show like this. do i need to re add zone from fresh start?
<img width="747" alt="image" src="https://github.com/apache/cloudstack/assets/122773216/278e8041-0946-4f52-bd01-2bc46009ebd3">

**Comment by kiranchavala** [comment]
@thorzinaung 

Yes, the system vm's should be in a running state, you can check the management server logs to see why there are not in running state

Please try to create a fresh setup, including the hypervisor, ( creating a new data center on VMware)

**Comment by thorzinaung** [comment]
hi @kiranchavala , i  just already done fresh setup but same issue. There was two system vm in the begining in a stopped state and it's gone after a few minutes. can i setup system vm manually?

**Comment by kiranchavala** [comment]
@thorzinaung 

Could you share in detail what steps you have performed when setting up Cloudstack 

Please refer to the documentation 

http://docs.cloudstack.apache.org/en/latest/installguide/management-server/index.html

**Comment by thorzinaung** [comment]
@kiranchavala hi, now issue has been resolved. I just forgot to readd my 2 volume. Now my both system vm is running.
