### ISSUE TITLE
viewer was disconnected

### ISSUE THREAD

**Issue by HtainL** [apache/cloudstack#7842]
##### ISSUE TYPE
 
 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other
 ~~~
Other
~~~

##### COMPONENT NAME

~~~
etc
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### CONFIGURATION
 
~~~
Advanced Networking
~~~
##### OS / ENVIRONMENT

~~~
ubuntu22.04 LTS
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~
In virt-manager, cloudstack vm can't open. As per photo, viewer was disconnected when choosing vnc server. With spice server in display, we can open our vm.  
~~~
![image](https://github.com/apache/cloudstack/assets/134905472/e69ce321-94a7-4384-9e7e-3ed3bfe7d351)
![image](https://github.com/apache/cloudstack/assets/134905472/4d2d8c27-978d-4627-bee3-c46c55ddf478)

**Comment by kiranchavala** [comment]
@HtainL are you able to open the console from the cloudstack ui 

![Screenshot 2023-08-10 at 5 05 03 PM](https://github.com/apache/cloudstack/assets/1401014/f891bf68-b1d8-4765-bdf8-529dd5aad7ed)

**Comment by HtainL** [comment]
@kiranchavala. Yes. Bro. I can open console from cloudstack ui. In kvm, i can't open console with vnc server that releated cloudstack vm.

**Comment by weizhouapache** [comment]
is `10.150.0.46` the ip of the kvm host ?

**Comment by nvazquez** [comment]
Hi @HtainL, this is actually not an issue, since 4.18.0 CloudStack is able to secure/encrypt the VNC access and uses the CA certificates used for securing the hosts to also secure the VNC traffic. The VNC client you are using seems to be only using the password but is not asking for the certificates, you may try another VNC client. Here is some related documentation: https://cwiki.apache.org/confluence/display/CLOUDSTACK/Secure+KVM+VNC+connection+using+the+CA+framework, https://www.shapeblue.com/secure-kvm-vnc-connections/

**Comment by havengit** [comment]
I am in the same situation. I can use the virt-viewer command instead of virt-manager to access the console remotely.
