### ISSUE TITLE
Host is showing as unsecure not matter how it is added. 

### ISSUE THREAD

**Issue by Fozzman** [apache/cloudstack#8379]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18.1
~~~

##### CONFIGURATION

One Management Server, One Database Server, One Host

##### OS / ENVIRONMENT

Ubuntu 22.04 LTS, KVM, MySQL 8.0

##### SUMMARY

This is not a bug, but was not sure how to categorize it. It is a problem that I am having with the latest rebuild of our system. This is the third or fourth time we have rebuilt it and the first time this issue has popped up. Our one and only host is showing up as unsecure, but connected. We have restarted the agent, management service, disconnected, and reconnected the host. As well as removed and readded the host. Each time it shows as unsecure. I am looking for pointers for things to look at to troubleshoot the issue. 

##### STEPS TO REPRODUCE

![image](https://github.com/apache/cloudstack/assets/105796625/37267314-62f6-422b-95c8-84d1aea5a633)

~~~
Added host both in the wizard and manually. 
~~~

##### EXPECTED RESULTS

~~~
I expect the host to show green 
~~~

##### ACTUAL RESULTS

The host is showing as unsecure. 

~~~
See picture above, host shows as unsecure. 
~~~

**Comment by DaanHoogland** [comment]
@Fozzman is the host added with certificates created from the in the system configured root ca?

**Comment by Fozzman** [comment]
I am not sure if I can answer that. What I can say is that this is a base install and there was no configuration on my end to install a root CA. I did the same as the previous two installs as it pertains to steps taken and in those attempts, the host was able to be added with no issue.

From: dahn ***@***.***>
Date: Tuesday, December 19, 2023 at 8:14 AM
To: apache/cloudstack ***@***.***>
Cc: Fozzman ***@***.***>, Mention ***@***.***>
Subject: Re: [apache/cloudstack] Host is showing as unsecure not matter how it is added. (Issue #8379)

@Fozzman<https://github.com/Fozzman> is the host added with certificates created from the in the system configured root ca?

**Comment by JoaoJandre** [comment]
Hello @Fozzman, 

The `Unsecure` state in ACS indicates that the Libvirt service has been configured to start with TCP. For the host to be marked with the `Up` state, Libvirt must be configured to start with TLS. However, during installation of the ACS Agent for KVM, some sockets are automatically masked, including the TLS socket; making it necessary to unmask them manually. To unmask the sockets and reestablish communication via TLS, the following steps are needed:

1. Unmask sockets:

```bash
systemctl unmask libvirtd-admin.socket
systemctl unmask libvirtd-ro.socket
systemctl unmask libvirtd-tcp.socket
systemctl unmask libvirtd-tls.socket
systemctl unmask libvirtd.socket
```

2. Stop the `libvirtd` service:

```bash
systemctl stop libvirtd
```

3. Start `libvirtd-tls.socket`

```bash
systemctl start libvirtd-tls.socket
```

4. Restart the ACS agent:

```bash
systemctl restart cloudstack-agent
```

5. Enable socket `libvirt-tls`

```bash
systemctl enable libvirtd-tls.socket
```

With this, Libvirt should start with TLS and ACS will mark it with the status `Up`, instead of `Unsecure`.
