### ISSUE TITLE
Error code: Start system VM (v-375-VM) Fail to start system vm

### ISSUE THREAD

**Issue by priyanshusingh-in** [apache/cloudstack#8984]
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
system VM
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.0
~~~

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

* Unable to start system VM after restarting my OS.
* Able to launch instances.
* Other Infrastructure is working fine.

![Screenshot 2024-04-26 103427](https://github.com/apache/cloudstack/assets/87827548/59e4d419-2915-4921-9271-2405e9f1f1fd)

**Comment by rohityadavcloud** [comment]
@priyanshusingh-in you'll need to read through the logs to see why is it failing, for example, you don't have enough VLANs or IP addresses, you don't have enough capacity (which could be CPU/RAM/disk space related) within the zone. Or some configuration related issues, which are specific to your environment.

Since you've mentioned you've restarted your OS, is that the hypervisor host or your management server host? What has changed.

**Comment by priyanshusingh-in** [comment]
I'm new to cloudstack and followed the quick installation guide to install it. can you provide some resources so I can learn and properly setup cloudstack. I am using CentOS running on VMware.

**Comment by rajujith** [comment]
@priyanshusingh-in  I am sharing some resources that should help you. 

https://www.youtube.com/watch?v=DlJg3LYvIIs

https://www.shapeblue.com/apache-cloudstack-poc-guide/

**Comment by weizhouapache** [comment]
@priyanshusingh-in 
is there any `Exception` in the file  `/var/log/cloudstack/management/management-server.log` ?

**Comment by priyanshusingh-in** [comment]
I think @rohityadavcloud is correct the problem lies with my hardware capacity as I am using CloudStack on CentOS 7 running on VMware on Windows 11. Hence, my memory usage is reaching 100% as I just have 8 GB ram on my PC.
Thanks everyone @rohityadavcloud @rajujith @weizhouapache .
