### ISSUE TITLE
Ui: Events related to system vm's are not shown

### ISSUE THREAD

**Issue by kiranchavala** [apache/cloudstack#9294]
ISSUE TYPE

Bug

COMPONENT NAME

Component: UI, Events

CLOUDSTACK VERSION

Cloudstack version 4.19.0

SUMMARY

Events related to system vm's are not shown

Steps to reproduce  the issue 

1. Navigate to  system vms ( console proxy, ssvm, rotuer vm) and check the events tab

Also try to destroy the system vm's  and cross check if the events are generated 

![Screenshot 2024-06-13 at 12 17 10 PM](https://github.com/apache/cloudstack/assets/1401014/26b1a167-abd1-4631-827b-222200408709)

![Screenshot 2024-06-13 at 12 24 43 PM](https://github.com/apache/cloudstack/assets/1401014/a436fd5c-7b1c-4de4-a24e-0904aacd6ce6)

![Screenshot 2024-06-24 at 3 57 43 PM](https://github.com/apache/cloudstack/assets/1401014/44422888-9d20-40a1-8978-49de36dc58bc)

Actual Behaviour 

The events related to system vm are not shown

Expected behaviour 

The events related to system vm should be shown

**Comment by harikrishna-patnala** [comment]
@kiranchavala I can see the events of system VMs on the operations like start,stop, reboot, etc

![image](https://github.com/user-attachments/assets/eb9a148c-a3b8-4406-ad28-2c98f917c3ec)


We are not able to see the destroy event because, we recreate the system VMs after it is destroyed, so we will get new system VMs with new IDs and UUIDs all together. So we don't see the destroy events of the old system VMs.

Hope I got it right.

**Comment by kiranchavala** [comment]
Thanks @harikrishna-patnala , 

Whenever systemvm are recreated , there is no create event logged 

1. Try to destroy the ssvm, cpvm, router.
2. When they are recreated again , there is no proxy.create event or ssvm.create logged

**Comment by harikrishna-patnala** [comment]
yes @kiranchavala that's because those are created internally by management server and not by any admin action. I don't think they are really necessary. If we want to see when is the system VM is created we still have created 
![Screenshot 2024-08-21 at 10 11 02 AM](https://github.com/user-attachments/assets/7b12c8cf-ac4d-4a8f-a714-1b6429507730)

**Comment by kiranchavala** [comment]
Thanks @harikrishna-patnala  , closing the issue
