### ISSUE TITLE
Can not change size root disk instances

### ISSUE THREAD

**Issue by leduyquy** [apache/cloudstack#9380]
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
Volume, Instances
~~~

##### CLOUDSTACK VERSION

~~~
 4.19.0.1 
~~~

##### OS / ENVIRONMENT

Ubuntu 22.04 for KVM, VMware 8.0

##### SUMMARY

Cannot resize root disk vm when compute offering with Disk offering strictness as false

##### STEPS TO REPRODUCE

~~~
Create Compute Offering
set root disk size 
set Disk offering strictness => false
~~~

##### EXPECTED RESULTS

~~~
When resize root disk see error bellow:
Failed to resize Root volume. The service offering of this Volume has been configured with a root disk size; on such case a Root Volume can only be resized when changing to another Service Offering with a Root disk size. For more details please check out the Official Resizing Volumes documentation.
~~~

##### ACTUAL RESULTS

~~~
Root Disk is resize to new size
~~~

**Comment by sureshanaparti** [comment]
able to reproduce this.

**Comment by harikrishna-patnala** [comment]
I think this is kind of design thing, the error message says 

"Failed to resize Root volume. The service offering of this Volume has been configured with a root disk size; on such case a Root Volume can only be resized when changing to another Service Offering with a Root disk size. For more details please check out the Official Resizing Volumes documentation."

For a Root volume having disk size mentioned in the offering can be resized only with offering change.

@leduyquy are you able to change the offering with a desired root disk size ?

**Comment by sureshanaparti** [comment]
The root disk resize for the disk with compute/service offering having root disk size and disk offering strictness - false, is allowed only through the other service offering with (new) root disk size. This is expected behavior.

https://github.com/apache/cloudstack/pull/9428 fixes issue, which checks the root disk size details in a different service offering (lookup with disk offering id of the root disk in service offering view).
