### ISSUE TITLE
Virtual Machine / Instance Settings Name values are not refreshing after adding one.

### ISSUE THREAD

**Issue by ffslcschools** [apache/cloudstack#9931]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.3
~~~

##### CONFIGURATION

~~~
UI bug not related to a specific configuration.
~~~

##### OS / ENVIRONMENT

~~~
Management server OS Ubuntu 24.04.01 LTS
Client browser Edge or Chrome Ver 130+
~~~

##### SUMMARY

~~~
When modifying virtual machine settings, after committing a setting the ui will not let you see new settings, only the last setting committed.
~~~

##### STEPS TO REPRODUCE

~~~
Add a setting and value to a virtual machine and click the green check.
Click add setting then click the Name field.
Only the previous setting will be displayed.
Leaving the current virtual machine view and going back, or deleting the added setting are the only way to get the settings list to come back.
~~~

##### EXPECTED RESULTS

~~~
To see the full list of Named settings so that another setting can be added.
~~~

##### ACTUAL RESULTS

~~~
Only the previously configured setting Name is listed.
~~~

**Comment by bernardodemarco** [comment]
@DaanHoogland, I believe this one is a duplicate ticket (see #8074), and its solution is already being addressed by #9683.

**Comment by DaanHoogland** [comment]
> @DaanHoogland, I believe this one is a duplicate ticket (see #8074), and its solution is already being addressed by #9683.

I think you are right. @JoaoJandre can we include that PR. @ffslcschools can you test #9683 ?

**Comment by ffslcschools** [comment]
@DaanHoogland I searched to see if this was out there and found nothing, I will go to the corner and think about what I have done. I will test that change if you will tell me where the file is.
I am no developer.

**Comment by JoaoJandre** [comment]
> @DaanHoogland I searched to see if this was out there and found nothing, I will go to the corner and think about what I have done. I will test that change if you will tell me where the file is. I am no developer.

@ffslcschools I'm not sure I got your question, but since it is only a UI change, it is somewhat easier to test, you can:
1. Clone the repository (`git clone git@github.com:apache/cloudstack.git`)
2. Fetch the changes from #9683 (`git fetch origin pull/9683/head:fix`)
3. Checkout the changes (`git checkout fix`)
4. Rename `ui/.env.local.example` to `ui/.env.local` and edit it so that it has the URL for your cloudstack instance
5. In the `ui` directory, run `npm install` and `npm run serve`, this last command will output a local URL for you to access the UI with the changes from #9683, than you can test if your problem was solved.

**Comment by JoaoJandre** [comment]
@DaanHoogland To move on with the release process, I'll merge #9683 and release the next RC. If @ffslcschools finds that the issue persists with #9683 and there is a next RC, the fix to might go into the next RC.  In any case this issue is not a blocker.
